name: interactive_media_gallery
description: Image and video preview component that supports zoom and drag
version: 1.0.5
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: "3.27.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
